In [52]:
print ("Thank you Hamoye!")

Thank you Hamoye!


print (single _underscore_ or single *asterisks*)

user bold **content**

In [6]:
import time
print (time.ctime())

Fri Jul 10 08:40:34 2020


In [54]:
import time
print("precise time concept: ", time.ctime())

precise time concept:  Thu Jul  9 16:58:52 2020


In [55]:
import math
print ("sqrt{3x + 2} + x^5")


sqrt{3x + 2} + x^5


In [56]:
print ("i love python " * 3)

i love python i love python i love python 


In [57]:
import numpy as np
arr= ([[4,5,4,5],[5,5,7,1],[71,54,2,100]])
mynumpy = np.array(arr)
print (mynumpy * 2)
print(mynumpy.dtype)
print(mynumpy.ndim)
print(mynumpy.shape)
print(type(mynumpy)     )
#np.random.random((3,2))=array([[1,5],[5,7],[71,100]])
#print(numpytest)


[[  8  10   8  10]
 [ 10  10  14   2]
 [142 108   4 200]]
int32
2
(3, 4)
<class 'numpy.ndarray'>


In [58]:
import numpy as np
test1 = np.array([[2,5],[5,7],[12,8]])
test2 = np.array([[5,1],[1,1],[2,3]])
sumtest = (test1+test2)
diftest = (test2-test1)
lords=(sumtest+diftest)
print(test1, "\n\n", test2,"\n\n",sumtest,"\n\n",diftest,"\n\n",lords)
print(limarray.shape)




[[ 2  5]
 [ 5  7]
 [12  8]] 

 [[5 1]
 [1 1]
 [2 3]] 

 [[ 7  6]
 [ 6  8]
 [14 11]] 

 [[  3  -4]
 [ -4  -6]
 [-10  -5]] 

 [[10  2]
 [ 2  2]
 [ 4  6]]
(3, 4)


In [59]:
import numpy as np
lima= ([[4,5,1,4],[5,8,7,1],[1,5,2,10]])
limarray = np.array(lima)
print(limarray)
print("\n", limarray[:2, :3])
print("\n",limarray<5)


[[ 4  5  1  4]
 [ 5  8  7  1]
 [ 1  5  2 10]]

 [[4 5 1]
 [5 8 7]]

 [[ True False  True  True]
 [False False False  True]
 [ True False  True False]]


In [10]:
import pandas as pd
userinfo = {
    'school': ['poly sec school', 'saint peters college', 'holy rosary college', 'dickson memorial college'],
    'name':['rabi', 'kerim', 'mary', 'justin'], 
    'age': [16, 14, 18, 19],
    'height': [88.2, 100.6, 95.0,112],
    'examtype': ['waec', 'jamb', 'gce', 'neco']   
}

userinfo_dataframe=pd.DataFrame(userinfo, index=[1,2,3,4,])
print('\n', userinfo_dataframe)
userinfo_dataframe = userinfo_dataframe.set_index('school')
userinfo_dataframe = userinfo_dataframe.drop('holy rosary college', axis=0)
print('\n', userinfo_dataframe)
userinfo_dataframe.to_csv(index) 


                      school    name  age  height examtype
1           poly sec school    rabi   16    88.2     waec
2      saint peters college   kerim   14   100.6     jamb
3       holy rosary college    mary   18    95.0      gce
4  dickson memorial college  justin   19   112.0     neco

                             name  age  height examtype
school                                                
poly sec school             rabi   16    88.2     waec
saint peters college       kerim   14   100.6     jamb
dickson memorial college  justin   19   112.0     neco


In [65]:
print(userinfo_dataframe['name'])
print("\n", userinfo_dataframe.loc[1])
print("\n", userinfo_dataframe.iloc[0])
print("\n", userinfo_dataframe['school'])
print(userinfo_dataframe.at[4, 'name'])
print(userinfo_dataframe.iat[0, 1])


1      rabi
2     kerim
3      mary
4    justin
Name: name, dtype: object

 school      poly sec school
name                   rabi
age                      16
height               88.2cm
examtype               waec
Name: 1, dtype: object

 school      poly sec school
name                   rabi
age                      16
height               88.2cm
examtype               waec
Name: 1, dtype: object

 1             poly sec school
2        saint peters college
3         holy rosary college
4    dickson memorial college
Name: school, dtype: object
justin
rabi


In [2]:
descdf = (userinfo_dataframe.describe())
print(descdf)


             age      height
count   4.000000    4.000000
mean   16.750000   98.950000
std     2.217356   10.069591
min    14.000000   88.200000
25%    15.500000   93.300000
50%    17.000000   97.800000
75%    18.250000  103.450000
max    19.000000  112.000000


In [22]:
import pandas as pd
import numpy as np
staffs = {
    'lecturers': ['Mr John', 'Mrs Rose', 'Mr Mike', 'Ms Robinson'],
    'courses': ['data science', np.nan, 'maths', 'english'],
    'salary': [140000, np.nan, 120000, 112000]
}
staffs_dataframe = pd.DataFrame(staffs, index=['level1','level2', 'level3', 'level4'])
print(staffs_dataframe)

          lecturers       courses    salary
level1      Mr John  data science  140000.0
level2     Mrs Rose           NaN       NaN
level3      Mr Mike         maths  120000.0
level4  Ms Robinson       english  112000.0


In [24]:
staffs_dataframe.to_csv('staffdt.csv', index=False)

In [7]:
import pandas as pd
FuelData = pd.read_csv('fuel_ferc1.csv')
print (FuelData)

                     record_id  utility_id_ferc1  report_year  \
0        f1_fuel_1994_12_1_0_7                 1         1994   
1       f1_fuel_1994_12_1_0_10                 1         1994   
2        f1_fuel_1994_12_2_0_1                 2         1994   
3        f1_fuel_1994_12_2_0_7                 2         1994   
4       f1_fuel_1994_12_2_0_10                 2         1994   
...                        ...               ...          ...   
29518  f1_fuel_2018_12_12_0_13                12         2018   
29519   f1_fuel_2018_12_12_1_1                12         2018   
29520  f1_fuel_2018_12_12_1_10                12         2018   
29521  f1_fuel_2018_12_12_1_13                12         2018   
29522  f1_fuel_2018_12_12_1_14                12         2018   

           plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
0                  rockport                coal       ton        5377489.0   
1      rockport total plant                coal       ton      

In [11]:
import os
print(os.getcwd())
print(os.listdir(os.getcwd()))

C:\Users\Opaluwa\Documents\Hamoye\notebooks
['.ipynb_checkpoints', 'fuel_ferc1.csv', 'HamoyeJupyter.ipynb', 'P12-50-Startups.csv', 'P12-SalaryData.csv', 'staffdt.csv', 'Untitled.ipynb', 'Working with numbers and logic.ipynb', 'works on string.py']


In [12]:
print(FuelData.describe(include='all'))

                      record_id  utility_id_ferc1   report_year  \
count                     29523      29523.000000  29523.000000   
unique                    29523               NaN           NaN   
top     f1_fuel_2010_12_281_2_6               NaN           NaN   
freq                          1               NaN           NaN   
mean                        NaN        118.601836   2005.806050   
std                         NaN         74.178353      7.025483   
min                         NaN          1.000000   1994.000000   
25%                         NaN         55.000000   2000.000000   
50%                         NaN        122.000000   2006.000000   
75%                         NaN        176.000000   2012.000000   
max                         NaN        514.000000   2018.000000   

       plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
count             29523               29523     29343     2.952300e+04   
unique             2315                   6    

In [14]:
print(FuelData.isnull().sum())

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64
